// Package brprocessor (Block Records Processor) is responsible for handling the
// ingestion and processing of block records from the network.
// This file (config.go) defines the configuration parameters that control
// the processor's resource usage, concurrency, and timeouts.
package brprocessor

import (
	"time"

	"github.com/Fantom-foundation/lachesis-base/inter/dag"
	"github.com/Fantom-foundation/lachesis-base/utils/cachescale"
	"github.com/syndtr/goleveldb/leveldb/opt"
)

// Config aggregates all configuration options for the Block Records Processor.
type Config struct {
	// BufferLimit sets the maximum number of items and total memory size for buffering
	// pending block records. This protects the node from running out of memory
	// if processing is slower than ingestion.
	BufferLimit dag.Metric

	// SemaphoreTimeout is the maximum duration the processor will wait to acquire
	// a processing slot or resource. If this timeout is reached, the operation
	// (typically enqueuing a new task) may fail or retry.
	SemaphoreTimeout time.Duration

	// MaxTasks defines the maximum number of concurrent processing tasks active
	// in the worker pool. This limits the CPU and I/O load generated by the processor.
	MaxTasks int
}

// DefaultConfig returns the standard configuration settings for the processor.
// It uses a `scale` function to adapt memory limits to the host machine's capabilities.
func DefaultConfig(scale cachescale.Func) Config {
	return Config{
		BufferLimit: dag.Metric{
			Num:  10000,                   // Allow buffering up to 10,000 records
			Size: scale.U64(15 * opt.MiB), // Limit buffer size to ~15 MiB (scaled)
		},
		SemaphoreTimeout: 10 * time.Second, // Timeout after 10 seconds waiting for resources
		MaxTasks:         512,              // Allow up to 512 concurrent processing tasks
	}
}
