// Package epprocessor (Epoch Packs Processor) handles the validation and application
// of epoch packs received from the network. Epoch packs contain the final state
// of an epoch and the necessary votes to prove its validity.
//
// This file (config.go) defines the configuration parameters that control the
// processor's resource limits, concurrency, and timeouts.
package epprocessor

import (
	"time"

	"github.com/Fantom-foundation/lachesis-base/inter/dag"
	"github.com/Fantom-foundation/lachesis-base/utils/cachescale"
	"github.com/syndtr/goleveldb/leveldb/opt"
)

// Config holds the tunable settings for the Epoch Pack Processor.
type Config struct {
	// BufferLimit sets the maximum number of items and total memory size for buffering
	// pending epoch packs. This prevents memory exhaustion if packs arrive faster
	// than they can be processed.
	BufferLimit dag.Metric

	// SemaphoreTimeout is the maximum time to wait for acquiring processing resources.
	// This ensures that the processor doesn't hang indefinitely if the system is overloaded.
	SemaphoreTimeout time.Duration

	// MaxTasks limits the number of concurrent processing tasks in the worker pool.
	// This controls the CPU and I/O load generated by epoch processing.
	MaxTasks int
}

// DefaultConfig returns the standard configuration for the Epoch Pack Processor.
// It accepts a `scale` function to adjust memory-related limits based on the host system's resources.
func DefaultConfig(scale cachescale.Func) Config {
	return Config{
		BufferLimit: dag.Metric{
			Num:  10000,                   // Allow buffering up to 10,000 epoch packs
			Size: scale.U64(15 * opt.MiB), // Limit buffer size to ~15 MiB (scaled)
		},
		SemaphoreTimeout: 10 * time.Second, // Timeout after 10 seconds if resources unavailable
		MaxTasks:         512,              // Allow up to 512 concurrent processing tasks
	}
}
